# netlify.toml (at repo root)

[build]
  # Install from repo root so npm workspaces are honored
  command = "npm ci && npm run -w apps/frontend build"
  publish = "apps/frontend/dist"

[build.environment]
  NODE_VERSION = "20"
  # Ensure optional deps (e.g., Rollup platform binary) are installed
  NPM_FLAGS = "--include=optional"

# SPA routing (served from publish dir)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
